{
    "brandId": 1,
    "data":  [
    {
        "name": "Avalanche",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1050,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000905"
    },
    {
        "name": "Avalanche",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1050,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000904"
    },
    {
        "name": "Avalanche",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "418х418",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000909"
    },
    {
        "name": "Avalanche",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "897,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000906"
    },
    {
        "name": "Avalanche",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "897,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000907"
    },
    {
        "name": "Avalanche",
        "status": "в наличии",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "897,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000908"
    },
    {
        "name": "Antique",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000743"
    },
    {
        "name": "Antique",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000744"
    },
    {
        "name": "Antique",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000746"
    },
    {
        "name": "Antique",
        "status": "в наличии",
        "mansory": "декоративная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000745"
    },
    {
        "name": "Alcazar",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000949"
    },
    {
        "name": "Alcazar",
        "status": "в наличии",
        "mansory": "декоративная",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000948"
    },
    {
        "name": "Allison",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1210,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000989"
    },
    {
        "name": "Briere",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000748"
    },
    {
        "name": "Briere",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1210,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000747"
    },
    {
        "name": "Briere",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "895,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000750"
    },
    {
        "name": "Briere",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "895,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000751"
    },
    {
        "name": "Toscana",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "300х600",
        "color": "светло-графитовый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000846"
    },
    {
        "name": "Toscana",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "300х600",
        "color": "графитовый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000845"
    },
    {
        "name": "Toscana",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "418х418",
        "color": "графитовый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000850"
    },
    {
        "name": "Toscana",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под бетон",
        "facture": "рельеф",
        "size": "300х600",
        "color": "графитовый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000847"
    },
    {
        "name": "Toscana",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "300х600",
        "color": "светло-графитовый",
        "country": "республика беларусь ",
        "price": "897,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000848"
    },
    {
        "name": "Marble",
        "status": "под заказ",
        "mansory": "облицовочная кладка",
        "coating": "матовое ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000804"
    },
    {
        "name": "Marble",
        "status": "в наличии ",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под мрамор ",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000739"
    },
    {
        "name": "Marble",
        "status": "под заказ",
        "mansory": "декор 1",
        "coating": "матовое ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000806"
    },
    {
        "name": "Marble",
        "status": "под заказ",
        "mansory": "декор 2",
        "coating": "матовое ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000805"
    },
    {
        "name": "Marble",
        "status": "под заказ",
        "mansory": "декор 3",
        "coating": "матовое ",
        "texture": "под мрамор ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000807"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "под мрамор",
        "size": "300х600",
        "color": "оливковый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000726"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "под мрамор",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000725"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "под мрамор",
        "size": "418х418",
        "color": "оливковый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "10",
        "articles": "УТ000000731"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "оливковый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000727"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "оливковый",
        "country": "республика беларусь ",
        "price": "1265,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000728"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "оливковый",
        "country": "республика беларусь ",
        "price": "863,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000730"
    },
    {
        "name": "Palissandro",
        "status": "под заказ",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "оливковый",
        "country": "республика беларусь ",
        "price": "863,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000729"
    },
    {
        "name": "Амалфи ",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое ",
        "texture": "под бетон ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000295"
    },
    {
        "name": "Амалфи ",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое ",
        "texture": "под бетон ",
        "facture": "гладкая",
        "size": "300х600",
        "color": "светло-серый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000539"
    },
    {
        "name": "Амалфи ",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под бетон ",
        "facture": "гладкая",
        "size": "418х418",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000001033"
    },
    {
        "name": "Амалфи ",
        "status": "в наличии",
        "mansory": "бордюр 1",
        "coating": "матовое ",
        "texture": "под бетон",
        "facture": "рельеф",
        "size": "95х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "374,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000328"
    },
    {
        "name": "Амалфи ",
        "status": "в наличии",
        "mansory": "бордюр 2",
        "coating": "матовое ",
        "texture": "под бетон",
        "facture": "рельеф",
        "size": "95х300",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "253,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000737"
    },
    {
        "name": "Амалфи ",
        "status": "в наличии",
        "mansory": "декор",
        "coating": "матовое ",
        "texture": "под бетон",
        "facture": "рельеф",
        "size": "300х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "897,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000090"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000553"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "300х600",
        "color": "коричневый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000555"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000680"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "коричневый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000693"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "бордюр",
        "coating": "глянцевое покрытие ",
        "texture": "под камень ",
        "facture": "гладкая",
        "size": "95х300",
        "color": "светло-бежевый (узор)",
        "country": "республика беларусь ",
        "price": "253,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000662"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под камень ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000686"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под камень ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000581"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие ",
        "texture": "под камень ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "коричневый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000564"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "декор 4",
        "coating": "глянцевое покрытие ",
        "texture": "под камень ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "863,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000627"
    },
    {
        "name": "Астерия",
        "status": "в наличии",
        "mansory": "декор 5",
        "coating": "глянцевое покрытие ",
        "texture": "под камень ",
        "facture": "рельеф",
        "size": "300х600",
        "color": "коричневый",
        "country": "республика беларусь ",
        "price": "863,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000626"
    },
    {
        "name": "Борнео",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000560"
    },
    {
        "name": "Борнео",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000681"
    },
    {
        "name": "Борнео",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000566"
    },
    {
        "name": "Борнео",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000567"
    },
    {
        "name": "Борнео",
        "status": "в наличии",
        "mansory": "декор 3",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000568"
    },
    {
        "name": "Брик",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000173"
    },
    {
        "name": "Брик",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое ",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "натурал",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000174"
    },
    {
        "name": "Брик",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000067"
    },
    {
        "name": "Брик",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000412"
    },
    {
        "name": "Брик",
        "status": "в наличии",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000079"
    },
    {
        "name": "Брик",
        "status": "в наличии",
        "mansory": "декор 4",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000080"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "декор 5",
        "coating": "матовое ",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "натурал",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000081"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 1",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000169"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 2",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000130"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 3",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000170"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 4",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000131"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 5",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000091"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 6",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000092"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 7",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000093"
    },
    {
        "name": "Брик",
        "status": "в наличиии",
        "mansory": "панно 8",
        "coating": "глянцевое покрытие",
        "texture": "под кирпич",
        "facture": "рельеф",
        "size": "300х600",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "391,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000094"
    },
    {
        "name": "Бари",
        "status": "ограниченная",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000558"
    },
    {
        "name": "Бари",
        "status": "ограниченная",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "300х600",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000557"
    },
    {
        "name": "Бари",
        "status": "ограниченная",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000622"
    },
    {
        "name": "Бари",
        "status": "ограниченная",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "мозайка",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000565"
    },
    {
        "name": "Бари",
        "status": "ограниченная",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "897,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000561"
    },
    {
        "name": "Дайкири",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000020"
    },
    {
        "name": "Дайкири",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000682"
    },
    {
        "name": "Дайкири",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000010"
    },
    {
        "name": "Дайкири",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "300х600",
        "color": "черный",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000011"
    },
    {
        "name": "Дайкири",
        "status": "в наличии",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "300х600",
        "color": "микс",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000009"
    },
    {
        "name": "Джерси",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000307"
    },
    {
        "name": "Джерси",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1189,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000692"
    },
    {
        "name": "Джерси",
        "status": "в наличии",
        "mansory": "бордюр",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "95х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "374,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000309"
    },
    {
        "name": "Джерси",
        "status": "в наличии",
        "mansory": "декор",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "300х600",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "863,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000308"
    },
    {
        "name": "Камелот",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "",
        "size": "300х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000408"
    },
    {
        "name": "Камелот",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "",
        "size": "300х600",
        "color": "светло-серый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "9",
        "articles": "УТ000000409"
    },
    {
        "name": "Камелот",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "",
        "size": "418х418",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1045,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000671"
    },
    {
        "name": "Камелот",
        "status": "в наличии",
        "mansory": "бордюр",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "95х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "374,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000411"
    },
    {
        "name": "Камелот",
        "status": "в наличии",
        "mansory": "декор",
        "coating": "глянцевое покрытие ",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "300х600",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "863,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000410"
    },
    {
        "name": "Верди",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "250х750",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1725,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000354"
    },
    {
        "name": "Верди",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "250х750",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1725,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000345"
    },
    {
        "name": "Верди",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1328,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000001031"
    },
    {
        "name": "Верди",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х750",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "2013,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000353"
    },
    {
        "name": "Верди",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х750",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "978,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000346"
    },
    {
        "name": "Норд",
        "status": "под заказ",
        "mansory": "облицовочная кладка",
        "coating": "матовое",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "250х750",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1725,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000942"
    },
    {
        "name": "Норд",
        "status": "под заказ",
        "mansory": "напольная",
        "coating": "матовое",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "500х500",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1450,0",
        "type": "кв. метр",
        "komplect": "6",
        "articles": "УТ000000607"
    },
    {
        "name": "Норд",
        "status": "под заказ",
        "mansory": "декор 1",
        "coating": "матовое",
        "texture": "под бетон",
        "facture": "гладкая",
        "size": "250х750",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1840,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000667"
    },
    {
        "name": "Норд",
        "status": "под заказ",
        "mansory": "декор 2",
        "coating": "матовое",
        "texture": "под бетон",
        "facture": "рельеф",
        "size": "250х750",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "2012,5",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000668"
    },
    {
        "name": "Травертин",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "250х750",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "1725,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000570"
    },
    {
        "name": "Травертин",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "500х500",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "1450,0",
        "type": "кв. метр",
        "komplect": "6",
        "articles": "УТ000000571"
    },
    {
        "name": "Травертин",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "матовое",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "250х750",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "978,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000563"
    },
    {
        "name": "Травертин",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "матовое",
        "texture": "под камень",
        "facture": "рельеф",
        "size": "250х750",
        "color": "кремовый",
        "country": "республика беларусь ",
        "price": "2013,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000569"
    },
    {
        "name": "Ливадия",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "моноколор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000289"
    },
    {
        "name": "Ливадия",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "моноколор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000679"
    },
    {
        "name": "Ливадия",
        "status": "в наличии",
        "mansory": "бордюр",
        "coating": "глянцевое покрытие ",
        "texture": "моноколор",
        "facture": "рельеф",
        "size": "54х500",
        "color": "камешки",
        "country": "республика беларусь ",
        "price": "230,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000278"
    },
    {
        "name": "Ливадия",
        "status": "в наличии",
        "mansory": "декор",
        "coating": "глянцевое покрытие ",
        "texture": "моноколор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000280"
    },
    {
        "name": "Ливадия",
        "status": "в наличии",
        "mansory": "панно 1",
        "coating": "глянцевое покрытие ",
        "texture": "моноколор",
        "facture": "гладкая",
        "size": "500х250",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000171"
    },
    {
        "name": "Ливадия",
        "status": "в наличии",
        "mansory": "панно 2",
        "coating": "глянцевое покрытие ",
        "texture": "моноколор",
        "facture": "гладкая",
        "size": "500х250",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000172"
    },
    {
        "name": "Крым",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие",
        "texture": "моноколор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000374"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000534"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000535"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000653"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "бордюр 1",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "54х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "230,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000536"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "бордюр 2",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "115х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "230,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000160"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "декор 1",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000176"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "декор 2",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000435"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "декор 3",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000436"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "декор 4",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000537"
    },
    {
        "name": "Дубай",
        "status": "в наличии",
        "mansory": "декор 5",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000538"
    },
    {
        "name": "Камелия",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000249"
    },
    {
        "name": "Камелия",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000250"
    },
    {
        "name": "Камелия",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000691"
    },
    {
        "name": "Камелия",
        "status": "в наличии",
        "mansory": "бордюр",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "54х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "230,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000253"
    },
    {
        "name": "Камелия",
        "status": "в наличии",
        "mansory": "декор",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "рельеф",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000255"
    },
    {
        "name": "Оникс",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "",
        "size": "250х500",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000232"
    },
    {
        "name": "Оникс",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "",
        "size": "418х418",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "1139,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000687"
    },
    {
        "name": "Оникс",
        "status": "в наличии",
        "mansory": "декор",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "",
        "size": "250х500",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000233"
    },
    {
        "name": "Оникс",
        "status": "в наличии",
        "mansory": "панно",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "",
        "size": "250х500",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000234"
    },
    {
        "name": "Оникс",
        "status": "в наличии",
        "mansory": "панно",
        "coating": "глянцевое покрытие ",
        "texture": "под мрамор",
        "facture": "",
        "size": "250х500",
        "color": "салатовый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000235"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое",
        "texture": "под песок",
        "facture": "гладкая",
        "size": "250х500",
        "color": "светло-бежевый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000252"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое",
        "texture": "под песок",
        "facture": "гладкая",
        "size": "250х500",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000251"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое",
        "texture": "под бетон  ",
        "facture": "гладкая",
        "size": "250х500",
        "color": "светло-серый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000385"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "облицовочная кладка",
        "coating": "матовое",
        "texture": "под бетон  ",
        "facture": "гладкая",
        "size": "250х500",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "1093,0",
        "type": "кв. метр",
        "komplect": "11",
        "articles": "УТ000000386"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "бордюр 1",
        "coating": "матовое",
        "texture": "под бетон  ",
        "facture": "рельеф",
        "size": "54х500",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "230,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000254"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "бордюр 2",
        "coating": "матовое",
        "texture": "под бетон  ",
        "facture": "рельеф",
        "size": "54х500",
        "color": "серый",
        "country": "республика беларусь ",
        "price": "230,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000066"
    },
    {
        "name": "Рамина",
        "status": "в наличии",
        "mansory": "декоративная",
        "coating": "матовое",
        "texture": "под бетон  ",
        "facture": "рельеф",
        "size": "250х500",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "575,0",
        "type": "поштучно",
        "komplect": "1",
        "articles": "УТ000000256"
    },
    {
        "name": "Полонез",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор",
        "facture": "глазур",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000665"
    },
    {
        "name": "Тароко",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "10",
        "articles": "УТ000000740"
    },
    {
        "name": "Поларис",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое",
        "texture": "под дерево",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000868"
    },
    {
        "name": "Ларго",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "10",
        "articles": "УТ000000690"
    },
    {
        "name": "Batu",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под асфальт",
        "facture": "глазур",
        "size": "418х418",
        "color": "асфальтовый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000899"
    },
    {
        "name": "Динара",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "10",
        "articles": "УТ000000720"
    },
    {
        "name": "Динара",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "венге",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "10",
        "articles": "УТ000000721"
    },
    {
        "name": "Магма",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "10",
        "articles": "УТ000000723"
    },
    {
        "name": "Base",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "натурал",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000754"
    },
    {
        "name": "Genesis",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "песочный",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000752"
    },
    {
        "name": "Modul",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "матовое ",
        "texture": "под дерево",
        "facture": "гладкая",
        "size": "418х418",
        "color": "дымчатый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000753"
    },
    {
        "name": "Glamour",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "белый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000783"
    },
    {
        "name": "Modena",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под мрамор",
        "facture": "гладкая",
        "size": "418х418",
        "color": "бежевый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000781"
    },
    {
        "name": "Mist",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "графитовый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000782"
    },
    {
        "name": "Maundays",
        "status": "в наличии",
        "mansory": "напольная",
        "coating": "глянцевое покрытие",
        "texture": "под камень",
        "facture": "гладкая",
        "size": "418х418",
        "color": "коричневый",
        "country": "республика беларусь ",
        "price": "1100,0",
        "type": "кв. метр",
        "komplect": "8",
        "articles": "УТ000000941"
    }
]
}